export enum TypesActions {
  AUTH_USER_LOGINED_ACTION = 'AUTH_USER_LOGINED_ACTION',
  AUTH_USER_REGISTERED_ACTION = 'AUTH_USER_REGISTERED_ACTION',
  AUTH_USER_SIGN_OUT_ACTION = 'AUTH_USER_SIGN_OUT_ACTION',
  AUTH_ERROR_ACTION = 'AUTH_ERROR_ACTION',
  AUTH_ERROR_UPLOADING_PROFILE_ACTION = 'AUTH_ERROR_UPLOADING_PROFILE_ACTION',
  AUTH_LOADING_ACTION = 'AUTH_LOADING_ACTION',

  HOME_LOADING_TOURNAMENTS_ACTION = 'HOME_LOADING_TOURNAMENTS_ACTION',
  HOME_LOADED_TOURNAMENTS_ACTION = 'HOME_LOADED_TOURNAMENTS_ACTION',
  HOME_ERROR_IN_LOADING_TOURNAMENTS_ACTION = 'HOME_ERROR_IN_LOADING_TOURNAMENTS_ACTION',
  HOME_CHANGE_REGION_ACTION = 'HOME_CHANGE_REGION_ACTION',
  HOME_CHANGE_FILTERS_ACTION = 'HOME_CHANGE_FILTERS_ACTION',
  HOME_NEW_MESSAGE_FROM_USER_ACTION = 'HOME_NEW_MESSAGE_FROM_USER_ACTION',

  USER_LOADING_USER_INFO_ACTION = 'USER_LOADING_USER_INFO_ACTION',
  USER_LOADED_TUSER_INFO_ACTION = 'USER_LOADED_TUSER_INFO_ACTION',
  USER_ERROR_IN_LOADING_USER_INFO_ACTION = 'USER_ERROR_IN_LOADING_USER_INFO_ACTION',
}
