export enum ActionTokens {
  AUTH_USER_LOGINED_ACTION = 'AUTH_USER_LOGINED_ACTION',
  AUTH_USER_REGISTERED_ACTION = 'AUTH_USER_REGISTERED_ACTION',
  AUTH_USER_SIGN_OUT_ACTION = 'AUTH_USER_SIGN_OUT_ACTION',
  AUTH_ERROR_ACTION = 'AUTH_ERROR_ACTION',
  AUTH_ERROR_UPLOADING_PROFILE_ACTION = 'AUTH_ERROR_UPLOADING_PROFILE_ACTION',
  AUTH_LOADING_ACTION = 'AUTH_LOADING_ACTION',
}
