export enum AuthActionTokens {
  USER_LOGINED_ACTION = 'USER_LOGINED_ACTION',
  USER_REGISTERED_ACTION = 'USER_REGISTERED_ACTION',
  USER_SIGN_OUT_ACTION = 'USER_SIGN_OUT_ACTION',
  AUTH_ERROR_ACTION = 'ERROR_ACTION',
}
