import { Events } from '../../../models'

export interface EventsState {
  error: string | null
  events: Array<Events>
}

export enum EventsActionsTypes {
  JOIN_TO_TOURNAMENT_ACTION = 'JOIN_TO_TOURNAMENT_ACTION',
  LEAVE_FROM_TOURNAMENT_ACTION = 'LEAVE_FROM_TOURNAMENT_ACTION',
  INIT_TOURNAMENT_PROFILE_ACTION = 'INIT_TOURNAMENT_PROFILE_ACTION',
  FETCH_TOURNAMENT_INFO_ACTION = 'FETCH_TOURNAMENT_INFO_ACTION',
  ERROR_FETCH_TOURNAMENT_INFO_ACTION = 'ERROR_FETCH_TOURNAMENT_INFO_ACTION',
}
